### PR TITLE
Improved Editing Interface

### PR DESCRIPTION
**Pull request by dendr01d**
The main thrust of this PR is to rework the editing window and add features, while incidentally adding extra backend functionality for handling bone information. Biggest points of interest:

- Application now natively supports native editing of optional subsets of bones (hrothgar, viera, IVCS) so long as they're defined in advance in the BoneData file. Anamnesis imports can detect and automatically enable these options
- Reversion functionality added to editing interface to "undo" changes. Works on individual vectors or all changes at once.
- Mirror mode added for simultaneous editing of left/right bone pairs (with care taken to keep rotation/position transforms symmetric)
- More safeguards surrounding saving/closing/etc to help prevent accidental deletions

My testing hasn't been especially robust, but just from playing around with things they seem to be working more or less how I'd expect. There's some weirdness surrounding Automatic Mode, but I have trouble reproducing it, and with more focus on a load/edit/save cycle it might not matter as much.

(Am I doing this right? I'm new to version control and the github ecosystem)

### CODE REVIEW

**Comment by StoiaCode** [comment]
Doing it very right! Looks good, I will test it in a bit and give feedback if it needs changes.

**Comment by StoiaCode** [comment]
Moved some small stuff around, otherwise I really like it! Especially the backup function sounds nice, ill test some more tomorrow and will merge in the evening if I dont find anything.

**Comment by dendr01d** [comment]
Messing around with things this morning I noticed and fixed a few bugs:
- IVCS bones apparently use different coordinate systems with a different kind of symmetry, so they have to be treated specially in mirror mode
- Extra bone options weren't being loaded from config because of the private accessors

**Comment by dendr01d** [comment]
Found a bug with the hash set, fixed by overriding BodyScales's equality function. Also added grouping to the editing interface so that bones are organized by "family" into collapsible subsections.

**Comment by StoiaCode** [comment]
Oh also while we are at this, we could implement #71 directly probably! I didnt get around to fix the merge conflicts yet but its nothing major.

**Pull request merged**
