### PR TITLE
Rework Underlying Data Structures

### PR DESCRIPTION
**Pull request by dendr01d**
Originally I just wanted to implement bone parenting, but along the way I got kind of frustrated at the code organization and ended up reworking a lot of the backend. To wit:

- BodyScales are now CharacterProfiles, renamed as such because they also accommodate translation and rotation. They act purely as data storage containers and get saved to disk as individual files instead of all being packed in with the plugin config. Date of creation is now an identifying field, meaning that it's possible for multiple profiles to share character names *and* profile names.
- Armatures now act as an interstitial medium between the plugin and the skeleton data in-game. They are built and rebuilt dynamically to reflect the live bone data of an individual entity (including the connections *between* the bones), and in turn handle the application of bone transformations.
- CharacterProfiles and Armatures are handled by their own respective Manager classes, each of which has an instance owned by the main Plugin class. All data operations are handled through the managers (for the most part), reducing the render loop of the program to "Which profiles are active -> which armatures have skeletons contained in game memory -> transform them".
- The plugin configuration file has been reduced to the general parameters of the plugin itself. Backward compatibility has been added so that any old configuration files (V0 or V2) are automatically updated to the new format and have their BodyScales cut out and converted to new CharacterProfiles.
- The various interfaces have been updated to reflect the use of the new data structures. I added a ctrl-Z-style "undo/redo" system to the editor window.
- In the move to using armatures, certain aspects of how transformations are applied have been adjusted -- scaling is now multiplicative and transforms are applied to every instance of each bone in the entire skeleton. I think this might alleviate some of the bugs people have reported but we'll see.

On that last note, there's still a bunch of stuff that needs to be polished up, but I wanted to get this draft up sooner than later.
- [ ] Certain editor window settings have been moved into a separate struct that persists on a per-session basis. Right now the way things are implemented between that and the profile manager mean only one editor window can be used at a time.
- [ ] The undo/redo system in the editing window sometimes interacts strangely with other operations. It needs a more robust (but still compact?) definition of how to track state changes that can be called for each operation and not just value edits
- [ ] I'd like to turn the main bit of the editing window into a proper table at some point, and adjust the headers to include icons that loosely indicate what the individual values represent
- [ ] At some point we probably need to add a separate options window to manage the configuration options that don't naturally fit in elsewhere (such as the location for saving profile data)
- [ ] The "default" profiles feature might be broken at the moment with the way the render loop works now, and fixing it probably warrants creating a more robust system of options for picking default profiles on a per-object-type basis, as well as choosing rendering options *for* each of those object types (not just NPCs/in cutscenes)
- [ ] Even though "duplicate" profiles are now possible, it may still be kind of confusing to sort through them? I added an info window so you can at least reference the date information, but it's still kind of confusing to figure out which is which. What's the bigger evil, though?
- [ ] I've been mostly hands off with the IPC stuff and don't even know if it's working properly right now -- I have no reason to think that it *shouldn't*, but confirming it is outside my wheelhouse at the moment.
- [ ] Bone parenting still isn't up and running :|

Due to the nature of the changes most of the initial bevy of commits aren't atomic in nature, but I tried to break things down as much as I could for clarity's sake.

### CODE REVIEW

**Comment by StoiaCode** [comment]
- [ ] We could instead do with a more clear duplicate handling. automatic (2) adding like windows, or something like that? 
- [ ] Yes we do absolutely need a settings menu.
- [ ] Honestly I may or may not have entirely forgotten that Default even exists until recently... so yeah will have to see how we tackle that. Honestly a bit over my head how to handle that for now...
- [ ] Only one Editor is actually not the worst;
- [ ] The profile data needs to be changed to the Config Directory
- [ ] Root scaling is is screwed again, quoting Alex: That means it doesn't ignore n_root bone scale when scaling bones and doesn't apply drawn model scale in render hook
- [ ] "Show Live bones" should probably be ticked by default, also I'd like to spark a discussion on if we just call it "Show all bones" with a tooltip telling the user "Showing all bones that are found on your model". Neither options are perfect imho but just a thought I had. 
- [ ] Is the = sign infront of the X Y Z ALL intended?

**Comment by AlexCSDev** [comment]
I think `DefaultProfileDirectory` should be replaced `DalamudServices.PluginInterface.ConfigDirectory`. We should not rely on that path never changing and instead leave it up to Dalamud developers to decide where configuration should be stored and how to handle any possible shenanigans related to it.

**Comment by AlexCSDev** [comment]
Non-player characters (retainers, NPCs) seems to be broken. Seems like C+ can't get skeleton for their GameObject.

That includes both applying the edits as well as editing window. (`show live bones` just shows empty list)

```02:21:30.443 | ERR [CustomizePlus] Error obtaining skeleton from GameObject '400D6665(XXXXXX - Retainer) at 216DB83FD10'
02:21:43.019 | ERR [CustomizePlus] Error in CustomizePlus render hook System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomizePlus.Data.Armature.ModelBone.ApplyModelTransform() in F:\Sources\FFXIV\CustomizePlusFolder\CustomizePlus\CustomizePlus\Data\Armature\ModelBone.cs:line 134
   at CustomizePlus.Data.Armature.Armature.ApplyTransformation() in F:\Sources\FFXIV\CustomizePlusFolder\CustomizePlus\CustomizePlus\Data\Armature\Armature.cs:line 250
   at CustomizePlus.Data.Armature.ArmatureManager.ApplyArmatureTransforms() in F:\Sources\FFXIV\CustomizePlusFolder\CustomizePlus\CustomizePlus\Data\Armature\ArmatureManager.cs:line 71
   at CustomizePlus.Data.Armature.ArmatureManager.RenderCharacterProfiles(CharacterProfile[] profiles) in F:\Sources\FFXIV\CustomizePlusFolder\CustomizePlus\CustomizePlus\Data\Armature\ArmatureManager.cs:line 22
   at CustomizePlus.Plugin.OnRender(IntPtr a1, Int64 a2) in F:\Sources\FFXIV\CustomizePlusFolder\CustomizePlus\CustomizePlus\Plugin.cs:line 325
.......
02:30:46.649 | INF [LOCALPLUGIN] Finished loading CustomizePlus.dll
02:31:05.582 | ERR [CustomizePlus] Error obtaining skeleton from GameObject ''
02:31:07.074 | ERR [CustomizePlus] Error obtaining skeleton from GameObject ''
02:31:07.241 | ERR [CustomizePlus] Error obtaining skeleton from GameObject ''
02:31:07.398 | ERR [CustomizePlus] Error obtaining skeleton from GameObject ''
02:31:46.564 | INF [LOCALPLUGIN] Unloading CustomizePlus.dll
02:31:47.567 | INF [LOCALPLUGIN] Finished unloading CustomizePlus.dll
02:31:47.879 | INF [LOCALPLUGIN] Loading CustomizePlus.dll
02:31:48.629 | INF [LOCALPLUGIN] Finished loading CustomizePlus.dll
02:32:10.858 | ERR [CustomizePlus] Error obtaining skeleton from GameObject ''
```

**Comment by StoiaCode** [comment]
The stack trace points to the same issue PCs have; where C+ tries to load their scales too early when they are not yet fully in memory. Not sure if that makes sense here tho. 

I'd like to think that a backup won't be needed but then again it never hurts to have one. We could move it to /temp/ I suppose? 
Something I was also thinking about is how if we have filed per scale now we can have rolling backups as well!

**Comment by StoiaCode** [comment]
I moved the PR from Main to its own branch, once the merge conflicts are resolved we can merge it for testing, that way we can simplify the process of co authering this rework :)

**Comment by AlexCSDev** [comment]
I took the liberty of merging latest changes from `main` into this PR in my own branch: https://github.com/AlexCSDev/CustomizePlus/tree/merge_main_changes_dendroid_pr. Any merge conflicts when merging should be forcibly resolved in favor of changes in my own branch.

Here are a few comments I have about this PR:
This PR introduces breaking changes to IPC, either api version bump will be required or handler for old version's data.

I also think we should drop following [SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1309.md) in favor of [CA1500](https://learn.microsoft.com/en-us/visualstudio/code-quality/ca1500?view=vs-2022&tabs=csharp) aka start private non-static field names with underscore and lowercase letter.

**Review by StoiaCode — APPROVED** [review]

**Pull request merged**
