### PR TITLE
Support for bone position and rotation offsets

### PR DESCRIPTION
**Pull request by AlexCSDev**
This PR implements ability to set position and rotation offsets for bones as well as position offset for the entire model. This is currently marked as draft PR because of known issues listed below. Everyone is welcome to help with those things by making PRs into the `position_rotation_support` branch in my fork.

Known issues:

- [x] Code needs to be rebased on top of latest commit.
- [x] Configuration file is not compatible with previous versions. Configuration converter needs to be implemented.
- [x] Position and rotation modes are using vector4 instead of vector3.
- [x] Rotation offsets are not compatible with GPose. Might also apply to position offsets.
- [x] Position and rotation offsets should be disabled when Anamnesis posing mode is enabled. Same goes for Ktisis once it gets required IPC.
- [x] IPC code is (partially) disabled and not tested.
- [x] Anamnesis import is not tested.
- [x] `IsApproximately` check is disabled and needs to be either removed completely or rewritten to properly support position, rotation and scale at the same time.

### CODE REVIEW

**Comment by AlexCSDev** [comment]
GPose seems to work fine as long as Ktisis and Anamnesis does not enable their posing modes. Since the models go absolutely haywire when those modes are enabled I propose we detect when those modes are enabled and disable all customize+ changes until those modes are disabled again. From what I've seen people are already more or less aware that customize+ does not have proper compatibility with those modes, so that shouldn't be a huge issue.

For Anamnesis this should be quite easy, we can just take anamnesis detection code from Ktisis. But for Ktisis itself we'll need to ask Ktisis team to implement IPC which will allow us to know when their posing mode is enabled.

**Comment by StoiaCode** [comment]
There is something to be said about this yes, Gpose behaviour has been wonky. The intended behaviour was that C+ will overwrite all changes made in Ana and other posing tools, no matter what. But it also appears to be the case quite often that instead it just straight up does not work in Gpose? If we where to decide on a consistent bahviour here it could be nice. 
Thought straight up disallowing scaling in Posing from C+ would mean we have to figure out how people get their scaling INTO Posing for them...

**Comment by AlexCSDev** [comment]
Should be ready for review. The only thing which isn't done is root bone offsets not working properly in cutscenes, but this is a job for separate PR because it needs quite a bit of research to figure out what is going on and not super critical.

**Comment by StoiaCode** [comment]
There appear to be some issues; At least when I build it.

1. Having multiple Scales for the same person (with the same name) will activate/deactivate both at once, instead of unselecting the other one like previous. 
2. In case of 1, if you then delete one scale it will nuke the first one in the list instead of the one you clicked at. 
3. The Converted scales have a Root scale of 0, causing the camera to fuck up and the name to float over the ground. Your character is not afflicted until you actually change the root scale, at which point you will poof out of existence until you increase it again. 
4. Trying to close a window of the Edit screen closes the first one that appeared, instead of the one you clicked (x) on. 
5. Automatic mode appears to be active no matter if its checked or not inside the Edit window, I must admit I never checked the how it was before this.

Thats what I found so far.

**Comment by StoiaCode** [comment]
Couldnt find any new issues, merging.

**Pull request merged**
