### PR TITLE
feat: adds apply scale by command

### PR DESCRIPTION
**Pull request by gahius**
Adds the possibility to apply Scales by command - this allowing to change Scales with macros and such
Tried to validate and user proof as much as possible
Please let me know if something needs changing/fixing
Ty!

### CODE REVIEW

**Comment by StoiaCode** [comment]
Two points (More like one split up):
- Right now it throws an error if you have a scale name twice.
- We may want/need a way to specifiy the Character name as well due to that. 
When creating a scale you have "Default" as name, which is fine since the Character name is what decides most. Many people will have multiple scales called Default for each Alt/Friend due to that. 
So something like `/Customize-apply Default Stoia-Flayh` would work (for the command spaces would need to be replaced since we allow spaces in Char name and Scale name).


Could also think about a command alias going /capply maybe?

**Comment by StoiaCode** [comment]
One thing I just got reminded about; Usernames can also contain dashes. 
So we may want to use underscores instead.

**Comment by gahius** [comment]
Updated!
- Changed the command parameters to {CharacterName},{ScaleName}
- Added some more validations (including multiple matches for same chara,scale - if that's even possible)
- Added alias /capply

**Comment by StoiaCode** [comment]
Heyhey! Sorry to bother you again, a HUGE PR just went through (#77), could you resolve the conflicts? Should not be TOO much work, probably just some tiny things.

**Comment by gahius** [comment]
> Heyhey! Sorry to bother you again, a HUGE PR just went through (#77), could you resolve the conflicts? Should not be TOO much work, probably just some tiny things.

Hey! No problem! Just merged, I'll do some tests ingame couple hours from now, if it all goes smooth I'll push

**Comment by StoiaCode** [comment]
Chears, feel free to also test the rest of the changes to your hearts content and report any issues! Reminder that for now Mare support is _severly_ broken. To non updated users, it will straight up refuse to be acceppted by mare luckily :)

**Comment by gahius** [comment]
Pushed! All seems to be Ok
Really liked the new table design! 👏

**Comment by StoiaCode** [comment]
Couldnt find more issues, merging.

**Pull request merged**
