### PR TITLE
Refactoring for consistent code style

### PR DESCRIPTION
**Pull request by AlexCSDev**
This includes .editorconfig, code cleanup and refactoring performed using Resharper. Work in progress.

### CODE REVIEW

**Comment by StoiaCode** [comment]
SIX THOUSAND CHANGES LMAO

**Comment by StoiaCode** [comment]
Is there a reason this is a Draft btw?

**Comment by AlexCSDev** [comment]
image
Pretty much this lmao. Will be done with this later today.

**Comment by StoiaCode** [comment]
Curious, it build in actions

**Comment by AlexCSDev** [comment]
That should be enough for now

**Pull request merged**
