### PR TITLE
Testing Branch Updates

### PR DESCRIPTION
**Pull request by dendr01d**
- Re-implements changes made in #139 (to the best of my understanding)
- Configuration settings converted to V3 from an older version will automatically have the old config file backed up
- As a temporary measure for the current round of testing, added an option on main menu to export current (V3) configuration as a V2 config file, to help out folks who didn't have backups

### CODE REVIEW

**Comment by chirpxiv** [comment]
Hi! Can you please add proper co-authorship of the re-implemented code?

**Comment by dendr01d** [comment]
Sure thing, what do I need to do?

**Comment by chirpxiv** [comment]
You can add a co-author by amending the relevant commit to include `Co-authored-by: chirp <ch1rp@protonmail.com>` under the commit message

**Comment by StoiaCode** [comment]
Lmk when that has happend.
There are also merge conflicts again, most likely due to the Cleanup PR?

**Pull request merged**
